In [1]:
# create an array from a list

my_list = [1,2,3]

In [2]:
import numpy as np

In [5]:
arr = np.array(my_list)

In [6]:
arr

array([1, 2, 3])

In [7]:
# matrix array

my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [8]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
# 2 sets of brackets denotes a 2-dimensional array

In [11]:
# how to use numpy methods to create arrays

np.arange(0,10)   # does not include last number

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
# specify the step size

np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [13]:
# generate array of all zeros
np.zeros(3)

array([ 0.,  0.,  0.])

In [15]:
# specify dimensions of zeros array
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [16]:
# generate array of ones
np.ones((3,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [17]:
# linspace returns evenly spaced numbers over an interval - similar, but different than a range
# takes in start,stop,number_of_points to evenly space numbers for

np.linspace(0,5,10)

array([ 0.        ,  0.55555556,  1.11111111,  1.66666667,  2.22222222,
        2.77777778,  3.33333333,  3.88888889,  4.44444444,  5.        ])

In [18]:
np.linspace(0,5,100)

array([ 0.        ,  0.05050505,  0.1010101 ,  0.15151515,  0.2020202 ,
        0.25252525,  0.3030303 ,  0.35353535,  0.4040404 ,  0.45454545,
        0.50505051,  0.55555556,  0.60606061,  0.65656566,  0.70707071,
        0.75757576,  0.80808081,  0.85858586,  0.90909091,  0.95959596,
        1.01010101,  1.06060606,  1.11111111,  1.16161616,  1.21212121,
        1.26262626,  1.31313131,  1.36363636,  1.41414141,  1.46464646,
        1.51515152,  1.56565657,  1.61616162,  1.66666667,  1.71717172,
        1.76767677,  1.81818182,  1.86868687,  1.91919192,  1.96969697,
        2.02020202,  2.07070707,  2.12121212,  2.17171717,  2.22222222,
        2.27272727,  2.32323232,  2.37373737,  2.42424242,  2.47474747,
        2.52525253,  2.57575758,  2.62626263,  2.67676768,  2.72727273,
        2.77777778,  2.82828283,  2.87878788,  2.92929293,  2.97979798,
        3.03030303,  3.08080808,  3.13131313,  3.18181818,  3.23232323,
        3.28282828,  3.33333333,  3.38383838,  3.43434343,  3.48

In [19]:
# create an identity matrix using numpy
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [20]:
# create random numbers

# create an array of random numbers uniformly distributed
np.random.rand(5)

array([ 0.21459434,  0.30629483,  0.11389962,  0.49496841,  0.51810778])

In [21]:
np.random.rand(5,5)

array([[ 0.1174152 ,  0.26023952,  0.36988308,  0.87885242,  0.48304636],
       [ 0.32579921,  0.44148466,  0.67984095,  0.70280178,  0.14921595],
       [ 0.98242979,  0.86079276,  0.64400104,  0.48764755,  0.46170122],
       [ 0.90998538,  0.65809976,  0.99693913,  0.23387865,  0.01084028],
       [ 0.46680706,  0.39552663,  0.5973879 ,  0.18905002,  0.88875309]])

In [22]:
# rand = generate numbers from a uniform distribution
# randn = generate numbers from a normal distribution
# randint = generate integer numbers from low to high number

np.random.randn(2)

array([-1.72846534,  0.68613702])

In [23]:
np.random.randn(4,4)

array([[-0.08755303, -0.84801165,  1.05018808, -0.73657776],
       [ 0.0166424 ,  1.48153177, -1.61325076, -0.88353304],
       [ 0.34214259,  1.27318106,  1.0106215 , -0.308256  ],
       [-1.32061908, -0.31942543,  0.2882922 ,  0.48579811]])

In [24]:
np.random.randint(1,100)

48

In [25]:
np.random.randint(1,100,10)

array([68, 96, 90, 80, 84, 30, 28, 16, 39, 67])

In [26]:
# attributes of an array

arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [27]:
ranarr = np.random.randint(0,50,10)
ranarr

array([43, 24, 23, 42,  6, 23, 22, 33, 11, 21])

In [28]:
# reshape method - pass arguments to define size of new array

arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [29]:
# digits / array passing in must fit size you specify
arr.reshape(4,5)

ValueError: total size of new array must be unchanged

In [30]:
# useful operations

ranarr.max()

43

In [31]:
ranarr.min()

6

In [32]:
# find index location of min/max value

ranarr

array([43, 24, 23, 42,  6, 23, 22, 33, 11, 21])

In [33]:
ranarr.argmax()

0

In [34]:
ranarr.argmin()

4

In [35]:
# find shape of a vactor

arr.shape

(25,)

In [36]:
arr = arr.reshape(5,5)
arr.shape

(5, 5)

In [37]:
# data type

arr.dtype

dtype('int32')

In [38]:
# if you don't want to type in 'np' in front of every command...

from numpy.random import randint

In [39]:
randint(2,10)

7